[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]    
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200